title: Vlad's Blog
name: "Uladzimir's Blog"
author: Uladzimir Yahorau
baseurl: "/vlad-blog"
description: Document my learning notes.
profile_url: "http://uladzimiryahorau.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
